/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1-214-g71889a8437-20250302"
#endif /* AVUTIL_FFVERSION_H */
